version: "3.9"  # optional since v1.27.0
services:
  bank-vanilla-mysql-server:
    image: mysql:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: bank-vanilla-mysql-server
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - bank-vanilla-mysql-server:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'Raven123qweasd*+'
      MYSQL_DATABASE: 'raven-dev'
      MYSQL_USER: 'raven-dev'
      MYSQL_PASSWORD: 'raven-dev*+'
    networks:
      - bank-vanilla-network

  bank-vanilla-migration-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bank-vanilla-migration-app
    restart: no
    container_name: bank-vanilla-migration-app
    command: sh -c "sleep 30 && /main.bin migrate up"
    depends_on:
      - bank-vanilla-mysql-server
    environment:
      GIN_MODE: 'release'
      LOG_LEVEL: 'debug'
      HOST: '0.0.0.0'
      DATASOURCE_DRIVER: 'mysql'
      DATASOURCE_USERNAME: 'root'
      DATASOURCE_PASSWORD: 'Raven123qweasd*+'
      DATASOURCE_SERVER: 'bank-vanilla-mysql-server:3306'
      DATASOURCE_SERVICE: 'raven-dev'
      DATASOURCE_URL: ':username::password@tcp(:server)/:service?charset=utf8&multiStatements=true&parseTime=True&loc=Local'
    networks:
      - bank-vanilla-network

  bank-vanilla-server-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bank-vanilla-server-app
    restart: unless-stopped
    container_name: bank-vanilla-server-app
    depends_on:
      - bank-vanilla-migration-app
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: 'release'
      LOG_LEVEL: 'debug'
      HOST: '0.0.0.0'
      DATASOURCE_DRIVER: 'mysql'
      DATASOURCE_USERNAME: 'root'
      DATASOURCE_PASSWORD: 'Raven123qweasd*+'
      DATASOURCE_SERVER: 'bank-vanilla-mysql-server:3306'
      DATASOURCE_SERVICE: 'raven-dev'
      DATASOURCE_URL: ':username::password@tcp(:server)/:service?charset=utf8&multiStatements=true&parseTime=True&loc=Local'
    networks:
      - bank-vanilla-network

volumes:
  bank-vanilla-mysql-server:
    name: bank-vanilla-mysql-server

networks:
  bank-vanilla-network:
    name: bank-vanilla-network
    driver: bridge

