// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: resources/proto/bank.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BankApi_Login_FullMethodName        = "/BankApi/Login"
	BankApi_GetPrincipal_FullMethodName = "/BankApi/GetPrincipal"
)

// BankApiClient is the client API for BankApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankApiClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetPrincipal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Principal, error)
}

type bankApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBankApiClient(cc grpc.ClientConnInterface) BankApiClient {
	return &bankApiClient{cc}
}

func (c *bankApiClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, BankApi_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApiClient) GetPrincipal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Principal, error) {
	out := new(Principal)
	err := c.cc.Invoke(ctx, BankApi_GetPrincipal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankApiServer is the server API for BankApi service.
// All implementations must embed UnimplementedBankApiServer
// for forward compatibility
type BankApiServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetPrincipal(context.Context, *emptypb.Empty) (*Principal, error)
	mustEmbedUnimplementedBankApiServer()
}

// UnimplementedBankApiServer must be embedded to have forward compatible implementations.
type UnimplementedBankApiServer struct {
}

func (UnimplementedBankApiServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBankApiServer) GetPrincipal(context.Context, *emptypb.Empty) (*Principal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrincipal not implemented")
}
func (UnimplementedBankApiServer) mustEmbedUnimplementedBankApiServer() {}

// UnsafeBankApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankApiServer will
// result in compilation errors.
type UnsafeBankApiServer interface {
	mustEmbedUnimplementedBankApiServer()
}

func RegisterBankApiServer(s grpc.ServiceRegistrar, srv BankApiServer) {
	s.RegisterService(&BankApi_ServiceDesc, srv)
}

func _BankApi_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApiServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApi_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApiServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApi_GetPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApiServer).GetPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApi_GetPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApiServer).GetPrincipal(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BankApi_ServiceDesc is the grpc.ServiceDesc for BankApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BankApi",
	HandlerType: (*BankApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _BankApi_Login_Handler,
		},
		{
			MethodName: "GetPrincipal",
			Handler:    _BankApi_GetPrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resources/proto/bank.proto",
}
