// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/endpoints/rpc/types.go
//
// Generated by this command:
//
//	mockgen -package=rpc -destination ../core/endpoints/rpc/mocks.go -source ../core/endpoints/rpc/types.go
//

// Package rpc is a generated GoMock package.
package rpc
