// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/endpoints/types.go
//
// Generated by this command:
//
//	mockgen -package=endpoints -destination ../core/endpoints/mocks.go -source ../core/endpoints/types.go
//

// Package endpoints is a generated GoMock package.
package endpoints
