// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/services/types.go
//
// Generated by this command:
//
//	mockgen -package=services -destination ../core/services/mocks.go -source ../core/services/types.go
//

// Package services is a generated GoMock package.
package services
